name: Assert Branch Naming Convention
on:
  pull_request:
    types: [opened]
jobs:
  branch_name:
    runs-on: ubuntu-latest
    name: Branch Name
    steps:
      - uses: AlbertHernandez/branch-name-action@v1.0.2
        with:
          branch_pattern: 'feat|fix|docs|style|docs|refactor|perf|test|build|ci|chore|revert'
          comment_for_invalid_branch_name: 'Please correct branch name!'
          fail_if_invalid_branch_name: 'true'
          ignore_branch_pattern: 'master|develop|staging'
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
