name: Release Drafter

on:
  push:
    branches:
      - master
      - develop

jobs:
  update_release_draft:
    name: "Release draft"
    runs-on: ubuntu-latest
    steps:
      - name: Release draft
        uses: release-drafter/release-drafter@v5.15.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
