name: Changelog CI

on:
  workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Run Changelog CI
        uses: saadmk11/changelog-ci@v1.0.0
        with:
          config_file: changelog-ci-config.yaml
          release_version: "V1.0.0"