name: Deploy docs to the wiki
on:
  workflow_dispatch:
jobs:
  publish_wiki:
    runs-on: ubuntu-latest
    steps:
    - name: Build and Deploy MkDocs
    - uses: mhausenblas/mkdocs-deploy-gh-pages@1.24
      run: |
        mkdocs build
        mkdocs serve

name: Publish docs via GitHub Pages
on:
  workflow_dispatch:

jobs:
  build:
    name: Deploy docs
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main
        uses: actions/checkout@v2

      - name: Deploy docs
        uses: mhausenblas/mkdocs-deploy-gh-pages@master
        # Or use mhausenblas/mkdocs-deploy-gh-pages@nomaterial to build without the mkdocs-material theme
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CUSTOM_DOMAIN: https://nikitha-r.github.io/ci_cd_pipeline_test/
          CONFIG_FILE: docs/mkdocs.yml
          EXTRA_PACKAGES: build-base
          # GITHUB_DOMAIN: github.myenterprise.com
          REQUIREMENTS: requirements.txt
